service: j-mail

provider:
  name: aws
  stage: ${opt:stage, ''}
  environment:
    MAIL_HOST: ${file(./config.${opt:stage, ''}.json):MAIL_HOST}
    MAIL_PORT: ${file(./config.${opt:stage, ''}.json):MAIL_PORT}
    MAIL_USER: ${file(./config.${opt:stage, ''}.json):MAIL_USER}
    MAIL_PASSWORD: ${file(./config.${opt:stage, ''}.json):MAIL_PASSWORD}
    MAIL_SECURE: ${file(./config.${opt:stage, ''}.json):MAIL_SECURE}
    DATABASE_URL: ${file(./config.${opt:stage, ''}.json):DATABASE_URL}
    JAWS_ACCOUNT_ID: ${file(./config.${opt:stage, ''}.json):JAWS_ACCOUNT_ID}
    JMAIL_QUEUE_URL: { Ref: JMailQueue }
  runtime: nodejs12.x
  profile: serverless-admin
  region: us-east-2

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sqs:SendMessage'
      Resource: 'arn:aws:sqs:${self:provider.region}:*:JMailQueue-${opt:stage}'

package:
  exclude:
    # Prisma needs some binaries. We don't care about the OSX binaries on AWS
    # and we end up with dupes, so we ignore all the query-engine bins except
    # one. If we don't do this, the package size ends up too large to deploy.
    - 'node_modules/**/query-engine-darwin'
    - 'node_modules/**/query-engine-rhel-openssl-1.0.x'
    - 'node_modules/**/libquery_engine-darwin-arm64.dylib.node'
    - 'node_modules/**/libquery_engine-rhel-openssl-1.0.x.so.node'
    - '!node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x'
    - '!node_modules/.prisma/client/libquery_engine-rhel-openssl-1.0.x.so.node'

functions:
  processJMailQueue:
    handler: src/handler.processJMailQueue
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - JMailQueue
              - Arn
          batchSize: 10
  sendUpdateEmails:
    handler: src/handler.sendUpdateEmails
    events:
      - schedule: cron(0 18 * * ? *)

resources:
  Resources:
    JMailQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: 'JMailQueue-${opt:stage}'
        RedrivePolicy:
          deadLetterTargetArn:
            'Fn::GetAtt':
              - JMailDeadLetterQueue
              - Arn
          maxReceiveCount: 3
    JMailDeadLetterQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: 'JMailDeadLetterQueue-${opt:stage}'
        MessageRetentionPeriod: 1209600

plugins:
  - serverless-plugin-typescript
