-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "BadgeType" ADD VALUE 'DEFAULT';
ALTER TYPE "BadgeType" ADD VALUE 'SPAM_REPORTER';
ALTER TYPE "BadgeType" ADD VALUE 'THREEHUNDREDFIFTY_POSTS';
ALTER TYPE "BadgeType" ADD VALUE 'FIVEHUNDRED_POSTS';
ALTER TYPE "BadgeType" ADD VALUE 'NOVELIST';
ALTER TYPE "BadgeType" ADD VALUE 'MULTILINGUAL';
ALTER TYPE "BadgeType" ADD VALUE 'POLYGLOT';
ALTER TYPE "BadgeType" ADD VALUE 'HELPER';
ALTER TYPE "BadgeType" ADD VALUE 'ONETHOUSANDFIVEHUNDRED_COMMENTS';
ALTER TYPE "BadgeType" ADD VALUE 'TWOTHOUSAND_COMMENTS';
ALTER TYPE "BadgeType" ADD VALUE 'TWOTHOUSANDFIVEHUNDRED_COMMENTS';
ALTER TYPE "BadgeType" ADD VALUE 'FIVETHOUSAND_COMMENTS';
ALTER TYPE "BadgeType" ADD VALUE 'CORRECT_FIVEHUNDRED_POSTS';
ALTER TYPE "BadgeType" ADD VALUE 'CORRECT_ONETHOUSAND_POSTS';
ALTER TYPE "BadgeType" ADD VALUE 'TEN_POST_COMMENTS';
ALTER TYPE "BadgeType" ADD VALUE 'FIFTY_POST_COMMENTS';
ALTER TYPE "BadgeType" ADD VALUE 'ONEHUNDRED_POST_COMMENTS';
ALTER TYPE "BadgeType" ADD VALUE 'TWOHUNDRED_POST_COMMENTS';
ALTER TYPE "BadgeType" ADD VALUE 'THREEHUNDRED_POST_COMMENTS';
ALTER TYPE "BadgeType" ADD VALUE 'TWOTHOUSANDTWOHUNDREDFIFTY_THANKS';
ALTER TYPE "BadgeType" ADD VALUE 'TWOTHOUSANDFIVEHUNDRED_THANKS';
ALTER TYPE "BadgeType" ADD VALUE 'FIVETHOUSAND_THANKS';
ALTER TYPE "BadgeType" ADD VALUE 'TENTHOUSAND_THANKS';
ALTER TYPE "BadgeType" ADD VALUE 'TEN_THANKS_GIVEN';
ALTER TYPE "BadgeType" ADD VALUE 'FIFTY_THANKS_GIVEN';
ALTER TYPE "BadgeType" ADD VALUE 'ONEHUNDRED_THANKS_GIVEN';
ALTER TYPE "BadgeType" ADD VALUE 'TWOHUNDREDFIFTY_THANKS_GIVEN';
ALTER TYPE "BadgeType" ADD VALUE 'FIVEHUNDRED_THANKS_GIVEN';
ALTER TYPE "BadgeType" ADD VALUE 'ONETHOUSAND_THANKS_GIVEN';
ALTER TYPE "BadgeType" ADD VALUE 'TWOTHOUSANDTWOHUNDREDFIFTY_THANKS_GIVEN';
ALTER TYPE "BadgeType" ADD VALUE 'TWOTHOUSANDFIVEHUNDRED_THANKS_GIVEN';
ALTER TYPE "BadgeType" ADD VALUE 'FIVETHOUSAND_THANKS_GIVEN';
ALTER TYPE "BadgeType" ADD VALUE 'TENTHOUSAND_THANKS_GIVEN';
ALTER TYPE "BadgeType" ADD VALUE 'TRAIL_RUNNER';
ALTER TYPE "BadgeType" ADD VALUE 'MOUNTAIN_CLIMBER';
