type greetings = {
  [key: string]: string
}

export const greetings: greetings = {
  Afrikaans: 'Hallo',
  Arabic: 'مرحبا',
  Azerbaijani: 'Salam',
  Basque: 'Kaixo',
  Catalan: 'Hola',
  Chechen: 'Салам',
  Cornish: 'Dydh da',
  Czech: 'Ahoj',
  Danish: 'Hej',
  Dutch: 'Hallo',
  English: 'Hello',
  Esperanto: 'Saluton',
  Estonian: 'Tere',
  Finnish: 'Moi',
  French: 'Bonjour',
  Galician: 'Ola',
  German: 'Hallo',
  Greek: 'Γειά σου',
  Hindi: 'हैलो',
  Hungarian: 'Szia',
  Icelandic: 'Halló',
  Indonesian: 'Halo',
  Irish: 'Dia dhuit',
  Italian: 'Ciao',
  Japanese: 'こんにちは',
  Korean: '안녕하세요',
  Latin: 'Salve',
  Macedonian: 'Здраво',
  'Mandarin Chinese': '你好',
  Norwegian: 'Hei',
  Persian: 'سلام',
  Polish: 'Witaj',
  Portuguese: 'Oi',
  Romanian: 'Buna',
  Russian: 'Привет',
  'Scots Gaelic': 'Halò',
  Spanish: 'Hola',
  Swahili: 'Halo',
  Swedish: 'Hej',
  Thai: 'สวัสดี',
  Turkish: 'Merhaba',
  Vietnamese: 'Chào',
}
