-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "BadgeType" ADD VALUE 'BUG_HUNTER';
ALTER TYPE "BadgeType" ADD VALUE 'TWENTY_POSTS';
ALTER TYPE "BadgeType" ADD VALUE 'FIFTY_POSTS';
ALTER TYPE "BadgeType" ADD VALUE 'SEVENTYFIVE_POSTS';
ALTER TYPE "BadgeType" ADD VALUE 'ONEHUNDREDFIFTY_POSTS';
ALTER TYPE "BadgeType" ADD VALUE 'TWOHUNDRED_POSTS';
ALTER TYPE "BadgeType" ADD VALUE 'TWOHUNDREDFIFTY_POSTS';
ALTER TYPE "BadgeType" ADD VALUE 'TEN_COMMENTS';
ALTER TYPE "BadgeType" ADD VALUE 'FIFTY_COMMENTS';
ALTER TYPE "BadgeType" ADD VALUE 'ONEHUNDRED_COMMENTS';
ALTER TYPE "BadgeType" ADD VALUE 'TWOHUNDREDFIFTY_COMMENTS';
ALTER TYPE "BadgeType" ADD VALUE 'FIVEHUNDRED_COMMENTS';
ALTER TYPE "BadgeType" ADD VALUE 'ONETHOUSAND_COMMENTS';
ALTER TYPE "BadgeType" ADD VALUE 'CORRECT_TEN_POSTS';
ALTER TYPE "BadgeType" ADD VALUE 'CORRECT_TWENTYFIVE_POSTS';
ALTER TYPE "BadgeType" ADD VALUE 'CORRECT_FIFTY_POSTS';
ALTER TYPE "BadgeType" ADD VALUE 'CORRECT_ONEHUNDRED_POSTS';
ALTER TYPE "BadgeType" ADD VALUE 'CORRECT_ONEHUNDREDFIFTY_POSTS';
ALTER TYPE "BadgeType" ADD VALUE 'CORRECT_TWOHUNDREDFIFTY_POSTS';
ALTER TYPE "BadgeType" ADD VALUE 'TEN_THANKS';
ALTER TYPE "BadgeType" ADD VALUE 'FIFTY_THANKS';
ALTER TYPE "BadgeType" ADD VALUE 'ONEHUNDRED_THANKS';
ALTER TYPE "BadgeType" ADD VALUE 'TWOHUNDREDFIFTY_THANKS';
ALTER TYPE "BadgeType" ADD VALUE 'FIVEHUNDRED_THANKS';
ALTER TYPE "BadgeType" ADD VALUE 'ONETHOUSAND_THANKS';
ALTER TYPE "BadgeType" ADD VALUE 'ONETHOUSANDTWOHUNDREDFIFTY_THANKS';
ALTER TYPE "BadgeType" ADD VALUE 'ONETHOUSANDFIVEHUNDRED_THANKS';
ALTER TYPE "BadgeType" ADD VALUE 'HIKER';
